package com.theokanning.openai.messages;

import com.theokanning.openai.threads.Attachment;
import lombok.*;

import java.util.List;
import java.util.Map;

/**
 * Creates a Message
 * <p>
 * https://platform.openai.com/docs/api-reference/messages/createMessage
 */
@Builder
@NoArgsConstructor
@AllArgsConstructor
@Data
public class MessageRequest {
    /**
     * The role of the entity that is creating the message.  Allowed values include:
     * user: Indicates the message is sent by an actual user and should be used in most cases to represent user-generated messages.
     * assistant: Indicates the message is generated by the assistant. Use this value to insert messages from the assistant into the conversation.
     */
    @NonNull
    @Builder.Default
    String role = "user";

    /**
     * The content of the message.
     */
    @NonNull
    String content;

    /**
     * A list of files attached to the message, and the tools they should be added to.
     */
    List<Attachment> attachments;


    /**
     * Set of 16 key-value pairs that can be attached to an object.
     * This can be useful for storing additional information about the object in a structured format.
     * Keys can be a maximum of 64 characters long, and values can be a maximum of 512 characters long.
     */
    Map<String, String> metadata;
}
